
LIST_PUBLIC_COLLECTION = 1
LIST_PRIVATE_COLLECTION = 2
LIST_WISH_LIST = 3
LIST_TRADING = 4

LIST_NAMES = (
    (LIST_PUBLIC_COLLECTION, "Public Collection"),
    (LIST_PRIVATE_COLLECTION, "Private Collection"),
    (LIST_WISH_LIST, "Wish List"),
    (LIST_TRADING, "Trading List"),
)

LIST_NAMES_DICT = dict(LIST_NAMES)  # e.g. LIST_NAMES_DICT[LIST_WANT] == "Want List"
